### ISSUE TITLE
Crash on Android when calling setupScanViewWithConfigJson

### ISSUE THREAD

**Issue by shubhnik** [Anyline/anyline-ocr-react-native-module#20]
```
05-19 21:01:52.297  30449-30449/com.masterymedia.fbascanner E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.masterymedia.fbascanner, PID: 30449
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZSt24__throw_out_of_range_fmtPKcz" referenced by "/data/app/com.masterymedia.fbascanner-1/lib/arm/libopencv_java3.so"...
            at java.lang.Runtime.loadLibrary(Runtime.java:372)
            at java.lang.System.loadLibrary(System.java:1076)
            at at.nineyards.anyline.camera.AnylineBaseView.<clinit>(SourceFile:49)
            at com.anyline.reactnative.AnylineOcrActivity.onCreate(AnylineOcrActivity.java:44)
            at android.app.Activity.performCreate(Activity.java:6303)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2376)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483)
            at android.app.ActivityThread.access$900(ActivityThread.java:153)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5438)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
```
Where could it be going wrong ?

**Comment by JonasLaux** [comment]
Hi @shubhnik ,
seems like some OpenCV Symbol could not be found. Have you implemented OpenCV in your application elsewhere?

**Comment by shubhnik** [comment]
@JonasLaux I am using other 3rd party RN libraries but can't say/nor think if someone is using openCV, I am getting error on this line https://github.com/Anyline/anyline-ocr-react-native-module/blob/master/android/src/main/java/com/anyline/reactnative/AnylineOcrActivity.java#L44 .

**Comment by JonasLaux** [comment]
@shubhnik sorry, but i can't give you any advice without knowing any environmental informations. Can you please provide your config/dependencies/implementation?

**Comment by shubhnik** [comment]
@JonasLaux 
### dependencies
```
"dependencies": {
    "anyline-ocr-react-native-module": "^3.12.0",
    "base-64": "^0.1.0",
    "crypto-js": "^3.1.9-1",
    "fast-xml-parser": "^2.2.1",
    "install": "^0.10.1",
    "react": "15.4.2",
    "react-native": "0.41.2",
    "react-native-animatable": "^1.2.0",
    "react-native-barcode": "^0.2.2",
    "react-native-barcode-scanner-universal": "^1.0.5",
    "react-native-barcodescanner": "^3.1.1",
    "react-native-camera": "^0.6.0",
    "react-native-fs": "^2.1.0-rc.1",
    "react-native-paypal-wrapper": "^1.0.0",
    "react-native-sqlite-storage": "^3.2.2",
    "react-native-stripe-api": "0.0.6",
    "react-native-vector-icons": "^4.0.0"
  }
```
### config file for Barcode
```
export default {
    license: "abc...."
    options: {
        "captureResolution":"1080p",
        "cutout": {
            "style": "rect",
            "maxWidthPercent": "80%",
            "alignment": "center",
            "ratioFromSize": {
                "width": 100,
                "height": 80
            },
            "strokeWidth": 4,
            "cornerRadius": 10,
            "strokeColor": "000000",
            "outerColor": "000000",
            "outerAlpha": 0.3,
            "feedbackStrokeColor": "0099FF"
        },
        "flash": {
            "mode": "manual",
            "alignment": "bottom_right"
        },
        "beepOnResult": true,
        "vibrateOnResult": true,
        "blinkAnimationOnResult": true,
        "cancelOnResult": false,
        "visualFeedback": {
            "style": "rect",
            "strokeColor": "0099FF",
            "fillColor": "220099FF",
            "animationDuration": 150
        }
    },
}
```
### implementation (I have a button on whose click this function is triggered)
```
openBarCodeScanner = () => {
        this.scanType = Constants.kScanType.kBarCode
        AnylineOCR.setupScanViewWithConfigJson(
            JSON.stringify(configBarcode),
            'BARCODE',
            this.onResult.bind(this),
            this.onError.bind(this)
        );
    };
```

**Comment by JonasLaux** [comment]
please try adding this to your gradle file:
`android.packagingOptions {
    pickFirst('lib/*/libopencv_java3.so')
}`

**Comment by shubhnik** [comment]
@JonasLaux It worked, Thank you very much :) :)
