### ISSUE TITLE
[Android] ActivityNotFoundException on calling setupScanViewWithConfigJson

### ISSUE THREAD

**Issue by edcrampin** [Anyline/anyline-ocr-react-native-module#32]
Hi,

I'm receiving this error upon calling setupScanViewWithConfigJson on Android.

```

E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
                  Process: com.--redacted--, PID: 13546
                  android.content.ActivityNotFoundException: Unable to find explicit activity class {com.--redacted--/com.anyline.reactnative.EnergyActivity}; have you declared this activity in your AndroidManifest.xml?
                      at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1815)
                      at android.app.Instrumentation.execStartActivity(Instrumentation.java:1531)
                      at android.app.Activity.startActivityForResult(Activity.java:4389)
                      at com.facebook.react.bridge.ReactContext.startActivityForResult(ReactContext.java:355)
                      at com.anyline.reactnative.AnylineSDKPlugin.scan(AnylineSDKPlugin.java:165)
                      at com.anyline.reactnative.AnylineSDKPlugin.routeScanMode(AnylineSDKPlugin.java:93)
                      at com.anyline.reactnative.AnylineSDKPlugin.setupScanViewWithConfigJson(AnylineSDKPlugin.java:87)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
                      at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
                      at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                      at android.os.Handler.handleCallback(Handler.java:751)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                      at android.os.Looper.loop(Looper.java:154)
                      at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
                      at java.lang.Thread.run(Thread.java:762)
```

Is there something that I haven't imported correctly? I believe I have followed all implementation instructions.

Thanks.

**Comment by JonasLaux** [comment]
hi,
can you please change "setupScanViewWithConfigJson" to "setup" or "setupPromise"?

**Comment by edcrampin** [comment]
Hi,

I'm still running v3.18, will be updating this to v3.19 shortly and will then migrate over to the new setup/setupPromise, however I don't think this is causing the issue.

**Comment by JonasLaux** [comment]
But in your node_modules the AndroidManifest of the plugin includes the EnergyActivity, like [here](https://github.com/Anyline/anyline-ocr-react-native-module/blob/release/3.18/android/src/main/AndroidManifest.xml#L10)?

**Comment by edcrampin** [comment]
Yep, AndroidManifest matches the repo but EnergyActivity doesnt appear to be found.

![image](https://user-images.githubusercontent.com/6486622/34117962-40fd0688-e415-11e7-8c03-a54e18a951d6.png)

**Comment by edcrampin** [comment]
Had to manually add EnergyActivity to my applications main AndroidManifest.xml in order for this to work - not sure this should be the intended solution but it has solved my issue.
