### ISSUE TITLE
"Plugin was not initialized" on Android release app

### ISSUE THREAD

**Issue by minhchienwikipedia** [Anyline/anyline-ocr-react-native-module#94]
**Anyline React-Native Plugin version:** 
23.0.0

**I'm submitting a ...**  
[ x] bug report
[ ] feature request
[ ] general question

**Occurring on ...**  
[ x] Android
[ ] iOS

**Current behavior:**
I'm getting an issue when I try to test Anyline on release, debug work as well, when I test on release my app crash!
`java.lang.RuntimeException: Unable to resume activity {com.test.dev/com.anyline.reactnative.Anyline4Activity}: java.lang.RuntimeException: Plugin was not initialized
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4060)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4092)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1991)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7258)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
     Caused by: java.lang.RuntimeException: Plugin was not initialized
        at io.anyline.view.ScanView.i(:16)
        at com.anyline.reactnative.Anyline4Activity.onResume(:88)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1416)
        at android.app.Activity.performResume(Activity.java:7633)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4052)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4092) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1991) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7258)`

**Expected behavior:**
Run without crash

**Steps to reproduce:**
Build release on android

**Comment by gseebacher** [comment]
Hi Duong,
do you use ProguardFiles? If yes, what does the file proguard-rules.pro contain?
Cheers
Gerhard

**Comment by minhchienwikipedia** [comment]
@gseebacher  yes, I'm using proguardFiles, this is my code in proguardFiles
```
-keep class com.facebook.hermes.unicode.** { *; }
-keep class com.facebook.jni.** { *; }
-keep class com.facebook.react.devsupport.** { *; }
-dontwarn com.facebook.react.devsupport.**
```

**Comment by gseebacher** [comment]
Hi Duong,
could you please try it with the latest version (24.2)?
Cheers
Gerhard

**Comment by minhchienwikipedia** [comment]
I can't remember how to resolve it but it works for now!
